spring:
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:postgresql://${HOST}:${DATABASE_PORT}/${DATABASE_NAME}

  jpa:
    open-in-view: off
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true